name: Sync Diff Files
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@master
        with:
          repository: emacsmirror/emacswiki.org
          ref: master
      - name: Checkout Repository to Copy Settings
        uses: actions/checkout@master
        with:
          path: dst
      - name: Copy Settings
        run: |
          mkdir -p .github
          cp dst/.github/sync.yml .github/
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          path: dst
          ref: master
      - name: Generate Diffs
        uses: mikefarah/yq@master
        with:
          cmd: |
            diffdir='.github/sync-diff'
            mkdir -p "${diffdir}"
            yq '.[].[]' .github/sync.yml | while read diff; do
              file="$(printf '%s' "${diff}" | sed 's#\.github/sync-diff/\(.*\)\.diff#\1#')"
              diff "dst/${file}" "${file}" > "${diff}"
            done
      - name: Run GitHub File Diff Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_BODY: 'synced local diff file(s) with [emacsmirror/emacswiki.org](${{ github.server_url }}/emacsmirror/emacswiki.org).'
