name: Sync Diff Files
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository to Copy Settings
        uses: actions/checkout@master
        with:
          ref: master
          path: repo
      - name: Checkout Source Repository
        uses: actions/checkout@master
        with:
          repository: emacsmirror/emacswiki.org
          ref: master
          path: emacswiki.org
      - name: Sync files
        run: |
          set -eux

          cp "./emacswiki.org/visws.el" "./repo/visws.el"

          (
              cd 'repo'
              git diff > ../sync.diff
              git checkout .
          )
          mv ./sync.diff ./repo/.github/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          branch: 'bot/update-diff'
          delete-branch: true
          labels: update
          path: repo
          title: 'Update .github/sync.diff by create-pull-request action'
